/** Starter random tables seeded into every new world. All original content; edit freely. */
export const DEFAULT_RANDOM_TABLES: { name: string; category: string; description: string; entries: (string | [string, number])[] }[] = [
  {
    name: "Given names",
    category: "names",
    description: "Generic first names for quick NPCs.",
    entries: [
      "Aldric", "Brisa", "Corwin", "Della", "Edric", "Fenna", "Garrick", "Hesper", "Ilsa", "Jorund", "Kestra", "Lorcan",
      "Maelis", "Nadine", "Osric", "Perrin", "Quilla", "Rowan", "Sabine", "Tobin", "Ulla", "Varis", "Wenna", "Yorick",
      "Zara", "Bram", "Cerys", "Dunstan", "Elowen", "Fitch", "Greer", "Hollis", "Isolde", "Jessamy", "Kael", "Linnea",
    ],
  },
  {
    name: "Family names",
    category: "names",
    description: "Surnames and bynames.",
    entries: [
      "Ashdown", "Blackbriar", "Coldwater", "Dunmere", "Emberly", "Fairweather", "Greaves", "Hollowell", "Ironside", "Juniper",
      "Kettle", "Larkspur", "Marrow", "Nettlefield", "Oakhart", "Pell", "Quarry", "Rook", "Saltmarsh", "Thorne",
      "Underhill", "Vance", "Wick", "Yarrow",
    ],
  },
  {
    name: "Complications",
    category: "complications",
    description: "Something goes sideways.",
    entries: [
      "A trusted contact asks for a favour first — and it's dangerous.",
      "The weather turns suddenly and badly.",
      "Someone recognises one of the party from an old incident.",
      "A rival group is after the same thing and is a step ahead.",
      "The reward turns out to be stolen property.",
      "A bystander gets hurt and needs help immediately.",
      "The local authorities want a bribe, a fee, or a confession.",
      "A key item breaks, goes missing, or is revealed as a fake.",
      "The guide is lying about how well they know the route.",
      "An old debt is called in at the worst moment.",
      "A child or animal follows the party and won't leave.",
      "The bridge, door, or passage they need is gone.",
      "A message arrives that changes what the party thought they knew.",
      "Someone is being framed — possibly the party.",
      "A festival, funeral, or riot fills the streets.",
      "The patron changes the terms of the deal.",
    ],
  },
  {
    name: "Tavern patrons",
    category: "patrons",
    description: "Who's drinking tonight.",
    entries: [
      "A soot-streaked miner spending a week's pay in one night",
      "Two off-duty guards arguing about a missing prisoner",
      "A traveling cartographer selling maps of dubious accuracy",
      "A grieving widow who keeps buying rounds for strangers",
      "A pilgrim who claims the end is near, cheerfully",
      "A card sharp running an honest game for once",
      "A retired adventurer with a missing hand and too many stories",
      "A merchant's apprentice sent to find 'capable people'",
      "A bard who only knows sad songs",
      "A hooded figure who hasn't touched their drink in an hour",
      "A pair of newlyweds who just eloped",
      "A tax collector everyone is pretending not to see",
      "A herbalist trading remedies for gossip",
      "A sailor with a strange coin they can't stop flipping",
    ],
  },
  {
    name: "Travel events",
    category: "travel",
    description: "Something on the road.",
    entries: [
      "An overturned cart; the driver is missing.",
      "A shrine with fresh offerings in the middle of nowhere.",
      "Tracks of something very large crossing the road.",
      "A toll checkpoint that wasn't here last month.",
      "Refugees heading the other way, carrying what they can.",
      "A lost messenger with a sealed letter.",
      "A ruined watchtower with smoke rising from it.",
      "A merchant caravan offering safety in numbers — for a price.",
      "The road is flooded; a ferryman offers a crossing.",
      "Wolves (or worse) follow at a distance for a day.",
      "An abandoned campsite with signs of a struggle.",
      "A friendly traveller who knows a shortcut.",
    ],
  },
  {
    name: "Wilderness events",
    category: "wilderness",
    description: "The wild is not empty.",
    entries: [
      "A sudden fog rolls in, thick enough to lose each other in.",
      "A spring of clear water — and something guarding it.",
      "A hunter's trap, recently sprung, with blood on it.",
      "Standing stones humming faintly at dusk.",
      "A rockslide blocks the path ahead.",
      "A wounded beast that won't attack unless cornered.",
      "Strange lights in the trees after dark.",
      "An old battlefield; rusted arms in the grass.",
      "A hermit who wants news of the world in exchange for directions.",
      "Signs of a camp: someone is tracking the party.",
    ],
  },
  {
    name: "Trinkets & loot",
    category: "loot",
    description: "Pocket contents and small finds.",
    entries: [
      "A tarnished locket containing a lock of red hair",
      "A tin whistle that sounds a note lower than it should",
      "A ledger page with three names crossed out",
      "A bone die that always rolls a four",
      "A key with no lock, wrapped in silk",
      "A child's drawing of a tall figure with no face",
      "A pressed flower that doesn't grow anywhere nearby",
      "A signet ring from a house that no longer exists",
      "A glass marble with a tiny storm inside",
      "A love letter, never sent",
      "A map fragment with a coastline no one recognises",
      "A pouch of seeds labelled 'do not plant'",
      ["A purse of mixed coin (2d10 silver)", 3],
      ["A few copper coins and lint", 4],
    ],
  },
  {
    name: "Treasure hoard extras",
    category: "treasure",
    description: "Flavour for a treasure find.",
    entries: [
      "A jewelled goblet engraved with a forgotten battle",
      "A bolt of fine dyed silk, slightly water-damaged",
      "A crown too small for any human head",
      "A chest of coins minted by a fallen kingdom",
      "An ornate music box that plays a lullaby",
      "A painted portrait with the eyes scratched out",
      "A set of silver cutlery for twelve, one fork missing",
      "Uncut gemstones in a leather pouch",
    ],
  },
  {
    name: "Rumour starters",
    category: "rumours",
    description: "Generic hearsay to adapt on the fly.",
    entries: [
      "Someone important has been seen meeting with strangers at night.",
      "The old mine/ruin/crypt has been reopened — by whom, no one says.",
      "Prices are about to rise; buy now.",
      "A noble's heir is not who they claim to be.",
      "The well water tastes wrong since the last storm.",
      "Soldiers are being quietly moved toward the border.",
      "A reward has been posted, but no one has come back to claim it.",
      "The temple's relic was replaced with a fake.",
      "A beast has been taking livestock, and it leaves no tracks.",
      "A ship came in with no crew aboard.",
    ],
  },
  {
    name: "Encounter seeds",
    category: "encounters",
    description: "Quick encounter prompts; stat them up from your bestiary.",
    entries: [
      "Bandits demand a toll — and they're desperate, not cruel.",
      "Scavengers fighting over a corpse.",
      "A patrol mistakes the party for wanted criminals.",
      "A territorial beast defending its young.",
      "Cultists performing a rite that's almost complete.",
      "An ambush at a narrow pass.",
      "Undead rising from a disturbed grave.",
      "A duel of honour that the party is asked to witness.",
    ],
  },
];
